import { h } from './superfine'

const isChildren = x => Array.isArray(x) || typeof x === 'string'

const vnode = tag => (props, children) => {
	const _props = props == null || (isChildren(props) && children == null)
		? {}
		: props
	const _children = isChildren(props) && children == null
		? props
		: children
	return h(tag, _props, _children)
}

export const a = vnode("a")
export const abbr = vnode("abbr")
export const address = vnode("address")
export const area = vnode("area")
export const article = vnode("article")
export const aside = vnode("aside")
export const audio = vnode("audio")
export const b = vnode("b")
export const base = vnode("base")
export const bdi = vnode("bdi")
export const bdo = vnode("bdo")
export const blockquote = vnode("blockquote")
export const body = vnode("body")
export const br = vnode("br")
export const button = vnode("button")
export const canvas = vnode("canvas")
export const caption = vnode("caption")
export const cite = vnode("cite")
export const code = vnode("code")
export const col = vnode("col")
export const colgroup = vnode("colgroup")
export const data = vnode("data")
export const datalist = vnode("datalist")
export const dd = vnode("dd")
export const del = vnode("del")
export const details = vnode("details")
export const dfn = vnode("dfn")
export const dialog = vnode("dialog")
export const div = vnode("div")
export const dl = vnode("dl")
export const dt = vnode("dt")
export const em = vnode("em")
export const embed = vnode("embed")
export const fieldset = vnode("fieldset")
export const figcaption = vnode("figcaption")
export const figure = vnode("figure")
export const footer = vnode("footer")
export const form = vnode("form")
export const h1 = vnode("h1")
export const h2 = vnode("h2")
export const h3 = vnode("h3")
export const h4 = vnode("h4")
export const h5 = vnode("h5")
export const h6 = vnode("h6")
export const header = vnode("header")
export const hr = vnode("hr")
export const i = vnode("i")
export const iframe = vnode("iframe")
export const img = vnode("img")
export const input = vnode("input")
export const ins = vnode("ins")
export const kbd = vnode("kbd")
export const label = vnode("label")
export const legend = vnode("legend")
export const li = vnode("li")
export const link = vnode("link")
export const main = vnode("main")
export const map = vnode("map")
export const mark = vnode("mark")
export const meta = vnode("meta")
export const meter = vnode("meter")
export const nav = vnode("nav")
export const object = vnode("object")
export const ol = vnode("ol")
export const optgroup = vnode("optgroup")
export const option = vnode("option")
export const output = vnode("output")
export const p = vnode("p")
export const param = vnode("param")
export const picture = vnode("picture")
export const pre = vnode("pre")
export const progress = vnode("progress")
export const q = vnode("q")
export const rp = vnode("rp")
export const rt = vnode("rt")
export const ruby = vnode("ruby")
export const s = vnode("s")
export const samp = vnode("samp")
export const section = vnode("section")
export const select = vnode("select")
export const small = vnode("small")
export const source = vnode("source")
export const span = vnode("span")
export const strong = vnode("strong")
export const style = vnode("style")
export const sub = vnode("sub")
export const summary = vnode("summary")
export const sup = vnode("sup")
export const svg = vnode("svg")
export const table = vnode("table")
export const tbody = vnode("tbody")
export const td = vnode("td")
export const template = vnode("template")
export const textarea = vnode("textarea")
export const tfoot = vnode("tfoot")
export const th = vnode("th")
export const thead = vnode("thead")
export const time = vnode("time")
export const title = vnode("title")
export const tr = vnode("tr")
export const track = vnode("track")
export const u = vnode("u")
export const ul = vnode("ul")
export const video = vnode("video")
export const wbr = vnode("wbr")
