import { h } from './superfine'

const isChildren = x => Array.isArray(x) || typeof x === 'string'

const vnode = tag => (props, children) => {
	const _props = props == null || (isChildren(props) && children == null)
		? {}
		: props
	const _children = isChildren(props) && children == null
		? props
		: children
	return h(tag, _props, _children)
}

export const a = vnode("a")
export const altGlyph = vnode("altGlyph")
export const altGlyphDef = vnode("altGlyphDef")
export const altGlyphItem = vnode("altGlyphItem")
export const animate = vnode("animate")
export const animateColor = vnode("animateColor")
export const animateMotion = vnode("animateMotion")
export const animateTransform = vnode("animateTransform")
export const circle = vnode("circle")
export const clipPath = vnode("clipPath")
export const colorProfile = vnode("color-profile")
export const cursor = vnode("cursor")
export const defs = vnode("defs")
export const desc = vnode("desc")
export const ellipse = vnode("ellipse")
export const feBlend = vnode("feBlend")
export const feColorMatrix = vnode("feColorMatrix")
export const feComponentTransfer = vnode("feComponentTransfer")
export const feComposite = vnode("feComposite")
export const feConvolveMatrix = vnode("feConvolveMatrix")
export const feDiffuseLighting = vnode("feDiffuseLighting")
export const feDisplacementMap = vnode("feDisplacementMap")
export const feDistantLight = vnode("feDistantLight")
export const feFlood = vnode("feFlood")
export const feFuncA = vnode("feFuncA")
export const feFuncB = vnode("feFuncB")
export const feFuncG = vnode("feFuncG")
export const feFuncR = vnode("feFuncR")
export const feGaussianBlur = vnode("feGaussianBlur")
export const feImage = vnode("feImage")
export const feMerge = vnode("feMerge")
export const feMergeNode = vnode("feMergeNode")
export const feMorphology = vnode("feMorphology")
export const feOffset = vnode("feOffset")
export const fePointLight = vnode("fePointLight")
export const feSpecularLighting = vnode("feSpecularLighting")
export const feSpotLight = vnode("feSpotLight")
export const feTile = vnode("feTile")
export const feTurbulence = vnode("feTurbulence")
export const filter = vnode("filter")
export const font = vnode("font")
export const fontFace = vnode("font-face")
export const fontFaceFormat = vnode("font-face-format")
export const fontFaceName = vnode("font-face-name")
export const fontFaceSrc = vnode("font-face-src")
export const fontFaceUri = vnode("font-face-uri")
export const foreignObject = vnode("foreignObject")
export const g = vnode("g")
export const glyph = vnode("glyph")
export const glyphRef = vnode("glyphRef")
export const hkern = vnode("hkern")
export const image = vnode("image")
export const line = vnode("line")
export const linearGradient = vnode("linearGradient")
export const marker = vnode("marker")
export const mask = vnode("mask")
export const metadata = vnode("metadata")
export const missingGlyph = vnode("missing-glyph")
export const mpath = vnode("mpath")
export const path = vnode("path")
export const pattern = vnode("pattern")
export const polygon = vnode("polygon")
export const polyline = vnode("polyline")
export const radialGradient = vnode("radialGradient")
export const rect = vnode("rect")
export const script = vnode("script")
export const set = vnode("set")
export const stop = vnode("stop")
export const style = vnode("style")
export const svg = vnode("svg")
export const switch_ = vnode("switch")
export const symbol = vnode("symbol")
export const text = vnode("text")
export const textPath = vnode("textPath")
export const title = vnode("title")
export const tref = vnode("tref")
export const tspan = vnode("tspan")
export const use = vnode("use")
export const view = vnode("view")
export const vkern = vnode("vkern")
